# Generated by Django 5.2.7 on 2025-10-22 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(choices=[('equipamento', 'Equipamento'), ('amuleto', 'Amuleto'), ('consumivel', 'Consumível'), ('outro', 'Outro')], max_length=20)),
                ('dano', models.IntegerField(blank=True, null=True)),
                ('defesa', models.IntegerField(blank=True, null=True)),
                ('durabilidade', models.IntegerField(blank=True, null=True)),
                ('slot_custo', models.PositiveIntegerField(blank=True, null=True)),
                ('efeito', models.TextField(blank=True, null=True)),
                ('exclusivo', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.categoria')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
