# Generated by Django 5.2.7 on 2025-10-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_tipo_alter_produto_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='exclusivo',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
