# Generated by Django 5.2.7 on 2025-10-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_produto_exclusivo_produto_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='produto',
            name='alma',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='seda',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
