# Generated by Django 5.2.7 on 2025-10-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_options_produto_alma_produto_seda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='defesa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
