# Generated by Django 5.2.7 on 2025-10-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_produto_defesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='alma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='seda',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
