# Generated by Django 5.2.7 on 2025-11-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_pedido_itempedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('C', 'Carrinho'), ('P', 'Pendente'), ('A', 'Aprovado'), ('E', 'Enviado'), ('F', 'Cancelado')], default='P', max_length=1),
        ),
    ]
