# Generated by Django 5.2.7 on 2025-11-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='imagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
