# Generated by Django 5.2.7 on 2025-11-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_itempedido_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('C', 'Carrinho'), ('P', 'Pendente'), ('A', 'Aprovado'), ('E', 'Enviado'), ('F', 'Cancelado')], default='C', max_length=1),
        ),
    ]
